#Portal Routing
from django.conf.urls import patterns, include, url
from django.views.generic import RedirectView
#from student import views

urlpatterns = patterns('student.views',
    url(r'^home$',                          'home',         name='home'),
    url(r'^studentresourcetype$',           'studentresourcetype',
                                                            name='studentresourcetype'),
    url(r'^resourcetype$',                  'resourcetype', name='resourcetype'),
    url(r'^workspace$',                     'workspace',    name='workspace'),
    url(r'^studentslist$',                  'studentslist', name='studentslist'),
    url(r'^assignedresourcelist$',  	    'assignedresourcelist',  
                                                            name='assignedresourcelist'),
    url(r'^studentprofile$',  		        'studentprofile',  
                                                            name='studentprofile'),
    url(r'^studentassignedresourcelist$',   'studentassignedresourcelist',  
                                                            name='studentassignedresourcelist'),
    url(r'^viewstudentresource$',           'viewstudentresource',  
                                                            name='viewstudentresource'),
    url(r'^viewstudentwrittenworks$',       'viewstudentwrittenworks',  
                                                            name='viewstudentwrittenworks'),
    url(r'^viewstudentwork$',               'viewstudentwork',  
                                                            name='viewstudentwork'),
    url(r'^worklistinfo$',                  'worklistinfo',  
                                                            name='worklistinfo'),
    url(r'^studentviewwork$',               'studentviewwork',  
                                                            name='studentviewwork'),
    url(r'^studentnoteslist$',              'studentnoteslist',  
                                                            name='studentnoteslist'),
    url(r'^studentwrittenwork$',            'studentwrittenwork',  
                                                            name='studentwrittenwork'),
    url(r'^studentviewassessments$',        'studentviewassessments',  
                                                            name='studentviewassessments'),
    url(r'^studentclassroom$',              'studentclassroom',  
                                                            name='studentclassroom'),
    url(r'^viewassignresource$',            'viewassignresource',  
                                                            name='viewassignresource'),
    url(r'^viewassignmentanswer',           'viewassignmentanswer',   
                                                            name='viewassignmentanswer'),
    url(r'^sticky-notes$',                  'stickynotes',  name='stickynotes'),
    url(r'^billboard$',                      'billboard',   name='billboard'),
    url(r'^billviewassignmentanswer$',       'billviewassignmentanswer',  
                                                            name='billviewassignmentanswer'),

)